# Generated by Django 3.1.3 on 2021-08-02 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20210729_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interact',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_user1', to='network.profile'),
        ),
        migrations.AlterField(
            model_name='interact',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_user2', to='network.profile'),
        ),
    ]
