# Generated by Django 3.1.3 on 2021-08-05 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20210804_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_user1', to='network.profile'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_user2', to='network.profile'),
        ),
    ]
