# Generated by Django 3.1.3 on 2021-09-18 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_auto_20210911_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follow',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_user2', to=settings.AUTH_USER_MODEL),
        ),
    ]
