# Generated by Django 3.1.3 on 2021-09-21 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_auto_20210921_1527'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
